language: php

php:
  - 5.3
  - 5.4

before_script:
  - pyrus install pecl/memcached
  - pyrus build pecl/memcached
  - echo "extension=memcached.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`

script: php -i