language: php

php:
  - 5.3
  - 5.4

before_script:
  - pyrus set php_ini `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - pyrus install pecl/memcached
  - pyrus build pecl/memcached

script: php -i